import io, os, uuid
from typing import List, Dict, Any, Optional

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from reportlab.lib.units import cm
from reportlab.lib.utils import ImageReader

from ..core.config import settings


def _coerce_dataframe(rows: List[Dict[str, Any]]) -> pd.DataFrame:
    df = pd.DataFrame(rows)
    # best-effort numeric coercion
    for col in df.columns:
        df[col] = pd.to_numeric(df[col], errors="ignore")
    return df


def summarize_dataframe(df: pd.DataFrame, numeric_fields: Optional[List[str]] = None) -> dict:
    if numeric_fields is None:
        num_cols = [c for c in df.columns if np.issubdtype(df[c].dtype, np.number)]
    else:
        num_cols = [c for c in numeric_fields if c in df.columns]

    summary = {}
    for c in num_cols:
        s = df[c].dropna()
        if s.empty:
            continue
        summary[c] = {
            "count": int(s.count()),
            "mean": float(s.mean()),
            "min": float(s.min()),
            "max": float(s.max()),
            "std": float(s.std(ddof=0)) if s.count() > 0 else 0.0,
        }
    return {"numeric_summary": summary, "row_count": int(len(df)), "columns": df.columns.tolist()}


def _make_chart(df: pd.DataFrame, numeric_fields: Optional[List[str]]) -> bytes:
    # choose first numeric column to plot
    if numeric_fields:
        cols = [c for c in numeric_fields if c in df.columns]
    else:
        cols = [c for c in df.columns if np.issubdtype(df[c].dtype, np.number)]
    if not cols:
        return b""

    col = cols[0]
    fig, ax = plt.subplots()
    ax.plot(df.index.to_list(), pd.to_numeric(df[col], errors="coerce").fillna(0).astype(float).to_list())
    ax.set_title(f"{col} over rows")
    ax.set_xlabel("Row #")
    ax.set_ylabel(col)
    buf = io.BytesIO()
    fig.savefig(buf, format="png", bbox_inches="tight", dpi=150)
    plt.close(fig)
    buf.seek(0)
    return buf.read()


def _generate_pdf(title: str, description: Optional[str], df: pd.DataFrame, insights: dict) -> tuple[str, str]:
    report_id = str(uuid.uuid4())[:8]
    os.makedirs(settings.REPORTS_DIR, exist_ok=True)
    out_path = os.path.join(settings.REPORTS_DIR, f"report_{report_id}.pdf")

    # chart image (optional)
    chart_bytes = _make_chart(df, insights.get("numeric_fields"))
    chart_img = ImageReader(io.BytesIO(chart_bytes)) if chart_bytes else None

    c = canvas.Canvas(out_path, pagesize=A4)
    width, height = A4

    # header
    c.setFont("Helvetica-Bold", 16)
    c.drawString(2 * cm, height - 2 * cm, title or "API Data Report")
    c.setFont("Helvetica", 10)
    c.drawString(2 * cm, height - 2.6 * cm, (description or "Generated by Report Generator"))

    # metrics
    c.setFont("Helvetica-Bold", 12)
    c.drawString(2 * cm, height - 3.5 * cm, "Key Metrics")
    c.setFont("Helvetica", 10)
    y = height - 4.1 * cm
    metrics = insights.get("numeric_summary", {})
    if metrics:
        for col, stats in metrics.items():
            line = (
                f"{col}: count={stats['count']}, mean={stats['mean']:.2f}, "
                f"min={stats['min']}, max={stats['max']}, std={stats['std']:.2f}"
            )
            c.drawString(2 * cm, y, line)
            y -= 0.6 * cm
            if y < 3 * cm:
                c.showPage()
                y = height - 2 * cm
    else:
        c.drawString(2 * cm, y, "No numeric columns detected for summary.")
        y -= 0.6 * cm

    # chart
    if chart_img:
        if y < 10 * cm:
            c.showPage()
            y = height - 2 * cm
        c.setFont("Helvetica-Bold", 12)
        c.drawString(2 * cm, y, "Visualization")
        y -= 0.8 * cm
        c.drawImage(chart_img, 2 * cm, y - 8 * cm, width=16 * cm, height=8 * cm, preserveAspectRatio=True, mask="auto")
        y -= 9 * cm

    # footer
    c.setFont("Helvetica-Oblique", 8)
    c.drawString(2 * cm, 1.5 * cm, "Report generated by ReportGeneratorServer • FastAPI")
    c.save()
    return out_path, report_id


def build_report(payload: dict) -> dict:
    title = payload.get("title") or "API Data Report"
    description = payload.get("description")
    rows = payload.get("data") or []
    numeric_fields = payload.get("numeric_fields")

    df = _coerce_dataframe(rows)
    insights = summarize_dataframe(df, numeric_fields=numeric_fields)
    insights["numeric_fields"] = numeric_fields

    pdf_path, report_id = _generate_pdf(title, description, df, insights)
    return {
        "report_id": report_id,
        "title": title,
        "pdf_path": pdf_path,
        "insights": insights,
    }
