from typing import Dict, Any, List
import numpy as np
import pandas as pd

from ..core.config import settings
from ..services.report_service import summarize_dataframe, build_report
from .llm import get_llm
from .tools.data_retriever import retrieve_data
from .tools.web_search import web_search
# from  tools.visualize import make_line_chart
from .tools.vizualize import make_line_chart
from .state import AgentState

# --- Data Retrieval Agent ---
def data_retrieval_node(state: AgentState) -> AgentState:
    rows = retrieve_data(
        query=state.get("query", ""),
        source_csv=state.get("params", {}).get("source_csv")
    )
    state["data_rows"] = rows
    msgs = state.get("messages", [])
    msgs.append(f"DataRetrieval: retrieved {len(rows)} rows.")
    state["messages"] = msgs
    return state

# --- Data Analysis Agent (LLM-guided, plus numeric summary) ---
def data_analysis_node(state: AgentState) -> AgentState:
    rows = state.get("data_rows", [])
    df = pd.DataFrame(rows) if rows else pd.DataFrame()
    insights = summarize_dataframe(df, numeric_fields=state.get("params", {}).get("numeric_fields"))
    state["data_summary"] = insights

    llm = get_llm()
    sys_prompt = (
        "You are a senior data analyst. Given a table summary (numeric stats, columns, row count) and the user's query, "
        "write a crisp analysis: trends, outliers, and any missing context that may require web research."
    )
    query = state.get("query", "")
    content = f"QUERY:\n{query}\n\nSUMMARY:\n{insights}\n"
    msg = llm.invoke([("system", sys_prompt), ("user", content)])
    state["analysis_text"] = msg.content if hasattr(msg, "content") else str(msg)
    msgs = state.get("messages", [])
    msgs.append("DataAnalysis: analysis_text generated.")
    state["messages"] = msgs
    return state

# --- Web Search Agent ---
def web_search_node(state: AgentState) -> AgentState:
    params = state.get("params", {})
    use_web = bool(params.get("use_web", False))
    query = state.get("query", "")
    if not use_web or not query:
        state["web_results"] = []
        return state
    results = web_search(query)
    state["web_results"] = results
    msgs = state.get("messages", [])
    msgs.append(f"WebSearch: got {len(results)} results.")
    state["messages"] = msgs
    return state

# --- Visualization Agent ---
def viz_node(state: AgentState) -> AgentState:
    rows = state.get("data_rows", [])
    numeric_field = state.get("params", {}).get("viz_numeric_field")
    img = make_line_chart(rows, numeric_field=numeric_field)
    state["viz_images"] = [img] if img else []
    msgs = state.get("messages", [])
    msgs.append(f"Visualization: {'1 chart' if img else 'no chart'}.")
    state["messages"] = msgs
    return state

# --- Report Generator Agent ---
def report_generator_node(state: AgentState) -> AgentState:
    rows = state.get("data_rows", [])
    title = state.get("params", {}).get("title") or "Agentic Report"
    description = state.get("analysis_text", "Generated by multi-agent pipeline.")

    payload: Dict[str, Any] = {
        "title": title,
        "description": description,
        "data": rows,
        "numeric_fields": state.get("params", {}).get("numeric_fields"),
    }
    result = build_report(payload)
    state["report_id"] = result["report_id"]
    state["report_path"] = result["pdf_path"]
    msgs = state.get("messages", [])
    msgs.append(f"ReportGenerator: created {result['pdf_path']}")
    state["messages"] = msgs
    return state
